### ISSUE TITLE
Description is required but not working

### ISSUE THREAD

**Issue by yui-har** [agileware-jp/redmine_issue_templates#18]
## Summary

A description is required, but you can create a template without inputting a description.

<img width="400" alt="issue_templates" src="https://user-images.githubusercontent.com/7232538/160348664-2d0029ce-a8fa-40e2-a3d9-a1d5b6fa7e6d.png">

<img width="400" alt="note_template" src="https://user-images.githubusercontent.com/7232538/160348846-d19b8e01-db1a-4483-9c2b-c7dd87e6a976.png">

## Environment

- Redmine version
4.2-stable
- Installed plugins
redmine_issue_templates: 0.3-stable(Maybe it also happens on the master branch)
- Ruby version
2.7.5-p203

**Comment by yui-har** [comment]
https://github.com/agileware-jp/redmine_issue_templates/commit/d7a5f93dbd2cb139630ae385b8d32ccff392fbd3#diff-8db2731eaed983a50f821e80de6e76c4f64c78e97912f2bdabd10010d9893a44
Committed on Jul 19, 2012. Changed `validates_presence_of` to `validates XXXXXXXXX, :presence => true`, but `validates :description, :presence` not added. (is it forget?)
<img width="779" alt="ScreenShot 2023-01-26 13 35 43" src="https://user-images.githubusercontent.com/7232538/214770473-b3d64909-a69e-41ab-82e6-cfe165b27328.png">
Perhaps other template models such as NoteTemplate and GlobalIssueTemplate are created by referring to (maybe copying and pasting?) this IssueTemplate.
Therefore, each model's attribute corresponding to `IssueTemplate#description` not exist `validates XXXXXXXXXXX, :presence => true`.

**Comment by yui-har** [comment]
@zh
Thank you for merging PR (#58 and #59).
If there are no problems, please close this issue.

**Comment by zh** [comment]
PR merged master and 0.3-stable branches.
