### ISSUE TITLE
Getting error while installing redmine_issue_templates on Redmine v5.0.2

### ISSUE THREAD

**Issue by mansoof-kazi** [agileware-jp/redmine_issue_templates#37]
## Summary

rake aborted!                                                                                                      LoadError: cannot load such file -- issue_templates/journals_hook                                                  /var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'                                            /var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'                                            /var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'                                     /opt/redmine/plugins/redmine_issue_templates/init.rb:25:in `<top (required)>'                                      /opt/redmine/lib/redmine/plugin_loader.rb:31:in `load'                                                             /opt/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'                                                  /opt/redmine/lib/redmine/plugin_loader.rb:108:in `each'                                                            /opt/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'                                                   /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `instance_exec'                /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'         /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'  /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_te/var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `catch'                        /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:603:in `block in default_terminator'  /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:199:in `block in halting'             /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `block in invoke_before'       /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `each'                         /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:512:in `invoke_before'                /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/callbacks.rb:105:in `run_callbacks'                /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:88:in `prepare!'                       /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'      /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'                           /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'                                     /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'               /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'                        /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'                              /opt/redmine/config/environment.rb:16:in `<top (required)>'                                                        /var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'                                            /var/lib/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'                                            /var/lib/gems/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'                                     /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'          /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'           /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'                   /opt/redmine/plugins/issue_recurring/lib/tasks/issue_recurring.rake:8:in `<top (required)>'                        /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `load'                      /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `block in load'             /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'           /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `load'                      /opt/redmine/lib/tasks/redmine.rake:218:in `block in <top (required)>'                                             /opt/redmine/lib/tasks/redmine.rake:218:in `each'                                                                  /opt/redmine/lib/tasks/redmine.rake:218:in `<top (required)>'                                                      /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `load'                      /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `block in load'             /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'           /var/lib/gems/2.7.0/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:326:in `load'                      /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:675:in `block in run_tasks_blocks'                     /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:675:in `each'                                          /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:675:in `run_tasks_blocks'                              /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/application.rb:528:in `run_tasks_blocks'                         /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/engine.rb:464:in `load_tasks'                                    /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/railtie.rb:207:in `public_send'                                  /var/lib/gems/2.7.0/gems/railties-6.1.6/lib/rails/railtie.rb:207:in `method_missing'                               /opt/redmine/Rakefile:7:in `<top (required)>'                                                                      /var/lib/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'                                             (See full trace by running task with --trace)                                                                      

## Environment

- Redmine version - 5.0.2
- Ruby version - 2.7.4
- OS Platform - Debian 11
- Database - MySQL v8
- Rails Env - 6.1.6

**Comment by ishikawa999** [comment]
@mansoof-kazi 
You are probably using an older version of the plugin that is not compatible with the latest Redmine.
Please do not specify a tag and get the latest code by command `git clone https://github.com/agileware-jp/redmine_issue_templates.git`

**Comment by zh** [comment]
New version released - [1.1.1](https://github.com/agileware-jp/redmine_issue_templates/releases/tag/1.1.1).
