### ISSUE TITLE
label_inherit_templates mistranslated in German

### ISSUE THREAD

**Issue by martinvonwittich** [agileware-jp/redmine_issue_templates#38]
## Summary

`label_inherit_templates` ("Inherit templates") is translated in German as "Vorlagen vererben", but should actually be translated as "Vorlagen erben".

## Description

`label_inherit_templates` ("Inherit templates") is translated in German as "Vorlagen vererben":

https://github.com/agileware-jp/redmine_issue_templates/blob/80c9ebfb4ab882a3c2c1072a364a8cfa29ec80d4/config/locales/de.yml#L29

This isn't actually the correct translation - "vererben" means "to bequeath", which is the inverse of "to inherit". So a German user will interpret the "Vorlagen vererben" checkbox as "subprojects will inherit the templates of this project", when the checkbox actually means "this project will inherit templates of its parent project", which is rather confusing.

## Environment

not really relevant

## Visual Proof / Screenshot

not really relevant

## Expected Results

`label_inherit_templates` should be translated in German as "Vorlagen erben".

## Actual Results

`label_inherit_templates` is translated in German as "Vorlagen vererben".

## Workaround

Get used to the mistranslation :D

**Comment by zh** [comment]
Merged
