### ISSUE TITLE
CircleCI "test" job failed with MySQL connection error

### ISSUE THREAD

**Issue by sanak** [agileware-jp/redmine_issue_templates#40]
## Summary

I am trying CircleCI (free plan) setup on my forked repository, but CircleCI "test" job failed with MySQL connection error.

## Description

The error message was as follows.
```
2022-11-08 23:02:56+00:00 [ERROR] [Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user
    Remove MYSQL_USER="root" and use one of the following to control the root user password:
    - MYSQL_ROOT_PASSWORD
    - MYSQL_ALLOW_EMPTY_PASSWORD
    - MYSQL_RANDOM_ROOT_PASSWORD

Exited with code 1
```

## Environment

- CircleCI (free plan)

## Visual Proof / Screenshot

None

## Expected Results

CircleCI "test" job should be passed.

## Actual Results

CircleCI "test" job failed.

## Workaround

None

**Comment by zh** [comment]
Merged
