### ISSUE TITLE
Please create a new tag (Based on the code after Redmine 5.0 support)

### ISSUE THREAD

**Issue by ishikawa999** [agileware-jp/redmine_issue_templates#42]
## Summary

The latest tag in this repository is 1.1.0, but the code in this tag is out of date and does not support Redmine 5.0.
Could you please create a 1.1.1 tag based on the latest code to avoid compatibility issues with Redmine 5.0 that occur when retrieving code from the latest tag?
I would also like to see the 0.3.9 tag added to 0.3-stable as well.

**Comment by zh** [comment]
New tags added - [0.3.9](https://github.com/agileware-jp/redmine_issue_templates/releases/tag/0.3.9) and [1.1.1](https://github.com/agileware-jp/redmine_issue_templates/releases/tag/1.1.1).
