### ISSUE TITLE
Note template sort order is not working

### ISSUE THREAD

**Issue by yui-har** [agileware-jp/redmine_issue_templates#47]
## Summary

You can select a note template when editing a note, but the sort order of the note template is ignored.

## Description

1. Create 3 note templates. (4, 5, 6)
2. Edit 2 note templates. (4, 5)
3. Select a note template when editing a note. However, the list of dialogs is displayed ignoring the sort order of the note templates. (6, 4, 5)

## Environment

- Redmine version : 5.0.3
- Installed plugins : redmine_issue_templates **0.3-stable** (maybe the **master** branch too)
- Ruby version : 3.1.3
- Database : PostgreSQL

### * Template list

<img width="641" alt="ScreenShot 2023-01-13 9 55 26" src="https://user-images.githubusercontent.com/7232538/212214959-112f4487-a9e3-48de-83b7-506dfa961fd8.png">

### * Select a note template (Different from the order in the template list above)

<img width="859" alt="ScreenShot 2023-01-13 9 59 29" src="https://user-images.githubusercontent.com/7232538/212215043-a8680d4b-6c7c-4011-80b3-ea5046b19990.png">

## Workaround

I think the cause is not using `scope :sorted` of app/models/note_template.rb.

**Comment by zh** [comment]
PR merged to both master and 0.3-stable branch.
