### ISSUE TITLE
Note template role setting disappears after changing sort order

### ISSUE THREAD

**Issue by yui-har** [agileware-jp/redmine_issue_templates#48]
## Summary

If you change the sorting order in the note template list, the role setting of the sorted template is disappeared.

## Description

1. Registered 3 note templates.
2. Edit a note template. (6: note-template-3) 
Set the following
* Templates visibility: "to these roles only"
* Role: Check on "Manager" and "Developer"
3. Change the sort position of 6:note-template-3.
4. After changing the sort position, looking at 6:note-template-3, the role setting is cleared.

## Environment

- Redmine version : 5.0.3
- Installed plugins : redmine_issue_templates **0.3-stable** (maybe the **master** branch too)
- Ruby version : 3.1.3
- Database : PostgreSQL

### * Before changing the sort position
<img width="661" alt="ScreenShot 2023-01-13 11 23 02" src="https://user-images.githubusercontent.com/7232538/212253392-e199a569-121a-4d84-8bdd-15be4e33d103.png">

### * Changing the sort position
<img width="641" alt="ScreenShot 2023-01-13 9 55 26" src="https://user-images.githubusercontent.com/7232538/212253456-0e5c2e61-77a9-483f-aa0a-d70fff352ab2.png">

### * After changing the sort position
<img width="661" alt="ScreenShot 2023-01-13 11 23 17" src="https://user-images.githubusercontent.com/7232538/212253512-bb289ba6-8aeb-4fd1-b673-7ba8149be48a.png">

## Workaround

I think changing these to the following will solve the problem.

```diff
diff --git a/app/controllers/note_templates_controller.rb b/app/controllers/note_templates_controller.rb
index 519da96..dc4b513 100644
--- a/app/controllers/note_templates_controller.rb
+++ b/app/controllers/note_templates_controller.rb
@@ -49,7 +49,7 @@ class NoteTemplatesController < ApplicationController
       if template_params.key?(:role_ids)
         template_params[:role_ids]
       else
-        @note_template.note_visible_role_ids
+        @note_template.note_visible_roles.pluck(:role_id)
       end

     save_and_flash(:notice_successful_update, :show)
```

0.3-stable branch
https://github.com/agileware-jp/redmine_issue_templates/blob/e0d1974f46d426fcf80c4544555bc26bf1668233/app/controllers/note_templates_controller.rb#L52

master branch
https://github.com/agileware-jp/redmine_issue_templates/blob/7c470025670b50277bfce04b53376415fe406da6/app/controllers/note_templates_controller.rb#L55

**Comment by zh** [comment]
PR merged to both master and 0.3-stable branches.
