### ISSUE TITLE
Is this plugin compatible with Redmine 4.2.x

### ISSUE THREAD

**Issue by gaurav-cointab** [agileware-jp/redmine_issue_templates#8]
Is this plugin compatible with Redmine 4.2.x?

If not, then do you know any way to use this plugin with 4.2.x with code changes or adding some codes in it.

**Comment by ishikawa999** [comment]
I'm using this plugin with Redmine 4.2 and it's working fine so far.

**Comment by JDQuackers** [comment]
> Is this plugin compatible with Redmine 4.2.x?
> 
> If not, then do you know any way to use this plugin with 4.2.x with code changes or adding some codes in it.

Yes it is compatible with 4.2.x -- I have the latest version 1.1.0 installed with 4.2.2-stable and had no issues

**Comment by zh** [comment]
New version released - [1.1.1](https://github.com/agileware-jp/redmine_issue_templates/releases/tag/1.1.1) - works with Redmine 4.2.x and 5.x.
