### ISSUE TITLE
[Support Request] Update the redmine project page of the plugin

### ISSUE THREAD

**Issue by naveenvalecha** [agileware-jp/redmine_issue_templates#90]
## Summary

Thanks for your work in the maintenance of the plugin. I understand that the maintenance is happening on github.
Could you update the redmine project page of the plugin https://www.redmine.org/plugins/redmine_issue_templates

## Environment

These informations are greatly helpful to support quickly.
You can get these informations from Redmine's information page.
(E.g. http://example.com/admin/info)

- Redmine version
- Installed plugins
- Ruby version
- OS Platform
- Database (MariaDB, MySQL, PostgreSQL) and its version
- Rails Env

## Visual Proof / Screenshot

When reporting an application error, post the error stack trace that 
you should find in the **log file** (eg. log/production.log). 

Screen shot would be also helpful.

## Workaround

Please let me know if you have any workaround.

**Comment by marji** [comment]
It seems the "Issue Templates" project page https://www.redmine.org/plugins/redmine_issue_templates now points back to github repo https://github.com/agileware-jp/redmine_issue_templates

Perhaps we can now close this issue?

**Comment by naveenvalecha** [comment]
Closing this issue as the Issue Templates redmine project page https://www.redmine.org/plugins/redmine_issue_templates  is pointing to this repo
